# Generated by spaday.cem from components.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any

from spaday.component import Child, Component

__all__ = ["RegularLayoutFrame", "SpadayRegularLayout"]


class SpadayRegularLayout(Component):
    """Resizable panel layout driven by a serializable split/tab tree."""

    tag = "spaday-regular-layout"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        layout: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "layout": layout,
            },
            **props,
        )


class RegularLayoutFrame(Component):
    """Named draggable panel frame inside a RegularLayout."""

    tag = "regular-layout-frame"

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        name: str | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "name": name,
            },
            **props,
        )
