# Generated by spaday.cem from components.cem.json — do not edit by hand.
from __future__ import annotations

from typing import Any

from spaday.catalog import ComponentSchema, PropertySchema
from spaday.component import Child, Component

__all__ = ["RegularLayoutFrame", "SpadayRegularLayout"]


class SpadayRegularLayout(Component):
    """Resizable panel layout driven by a serializable split/tab tree."""

    tag = "spaday-regular-layout"
    schema = ComponentSchema(
        tag="spaday-regular-layout",
        class_name="SpadayRegularLayout",
        summary="Resizable panel layout driven by a serializable split/tab tree.",
        props=(PropertySchema(name="layout", kind="json", choices=(), default=None, description="Serializable regular-layout split/tab tree."),),
        events=(),
        slots=("",),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        layout: Any = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "layout": layout,
            },
            **props,
        )


class RegularLayoutFrame(Component):
    """Named draggable panel frame inside a RegularLayout. Its content area (::part(container)) is display: block with a definite height, so slotted content fills it with height: 100%, not flex: 1."""

    tag = "regular-layout-frame"
    schema = ComponentSchema(
        tag="regular-layout-frame",
        class_name="RegularLayoutFrame",
        summary="Named draggable panel frame inside a RegularLayout. Its content area (::part(container)) is display: block with a definite height, so slotted content fills it with height: 100%, not flex: 1.",
        props=(PropertySchema(name="name", kind="string", choices=(), default=None, description="Panel name referenced by the layout tree."),),
        events=(),
        slots=("",),
    )

    def __init__(
        self,
        *children: Child,
        key: str | None = None,
        name: str | None = None,
        **props: Any,
    ) -> None:
        super().__init__(
            *children,
            key=key,
            props={
                "name": name,
            },
            **props,
        )
